### ISSUE TITLE
Any plan to support self-hosted Headscale server?

### ISSUE THREAD

**Issue by yqs112358** [ajitid/telltail-center#11]
[Headscale](https://github.com/juanfont/headscale) is an official-support, self-hosted implementation of the Tailscale control server. It allows users who are in an intranet or have a poor connection to the official Tailscale to set up their own Tailscale control server.

If there can be support to self-hosted Headscale server, it will be a great surprise to a large number of Tailscale lovers. 🥰

The work shouldn't be too complicated. I think it involves only some substitutions of URLs.

**Comment by ajitid** [comment]
Heya. I'm not planning to support Headscale. But feel free to hack on it and send a PR. I'll keep the issue open.

Headscale and Tailscale may share PRs with each other but I don't think Tailscale _officially_ supports it.
