### ISSUE TITLE
Installing Telltail Sync on macOS Fails - Segmentation Fault

### ISSUE THREAD

**Issue by rushvora** [ajitid/telltail-center#4]
Attempting to run `./telltail install sync --tailnet tailnet-name --device device-name` results in `[1]    33643 segmentation fault`.

I downloaded `telltail-cli-mac-amd64`, for a 2020 13" MBP.

Telltail Sync is up and running successfully on my other devices, Windows, iOS, and Linux, with successful copy pasting across them. Telltail Center is running on a Linux PC.

Let me know how I can help in debugging this issue.

**Comment by rushvora** [comment]
It's an Intel based Mac.

**Comment by ajitid** [comment]
Well that's unfortunate, as I don't own a Mac. So it'd be difficult for me to sort this issue out.

**Comment by rushvora** [comment]
I understand… any tips on how I can go about debugging this?

**Comment by doctopus** [comment]
I have the same error: segmentation fault when I am trying to install center using the command 
`./telltail install center --auth-key <auth-key>`

Mac Intel processor got the amd64 version of the app and renamed to telltail and gave permission chmod +x. Could you please suggest?

**Comment by ajitid** [comment]
@doctopus I don't own a Mac so I can't help you here, at least not right now. I am starting to suspect it is more of a binary issue than anything.

**Comment by ajitid** [comment]
@doctopus and @rushvora: I've updated Telltail, can you try again?

You can uninstall any leftover Telltail program [using this way](https://guide-on.gitbook.io/telltail/installation/uninstall) and setup Telltail again by following [this guide](https://guide-on.gitbook.io/telltail/installation/setup-telltail-center).

**Comment by doctopus** [comment]
Thank you for the update @ajitid 

I could not execute the uninstall command on the previously installed version of telltail. 
`./telltail uninstall center` command returned `1595 segmentation fault  ./telltail uninstall center`
and 
`./telltail uninstall sync` returned `1641 segmentation fault  ./telltail uninstall sync`

I went ahead with removing the file and install the new version. But at the `./telltail install center --auth-key <tailscale-auth-key>` step it opens a system pop up saying the file can not be opened, as follows.

![20240807 174652-CleanShot](https://github.com/user-attachments/assets/aafb6db2-cc18-4547-bdb3-600addac614c)

**Comment by ajitid** [comment]
This is a macOS thing. You have to 'open' it once before you can run any command. To do that, right click on Telltail and click Open.

<img width="374" alt="Screenshot 2024-08-08 at 5 03 04 AMx" src="https://github.com/user-attachments/assets/0b6ff5ae-2b55-42e6-8fc7-c4f92adbf998">

You would be able to run `./telltail install ` after it.

Also, this new telltail would be able to remove leftover too. Run [these commands](https://guide-on.gitbook.io/telltail/installation/uninstall) first before you run  `./telltail install ` commands

**Comment by doctopus** [comment]
Ok, I could do it but it had to be allowed from the Privacy and security menu after attempting to open once.
![20240807 202421-Privacy   Security](https://github.com/user-attachments/assets/04ecc53b-563e-4c5b-8ad7-c5a43d746003)

Installation of center went perfectly. But I am not able to access my tailnet url. Possibly a DNS propagation issue since I renamed my tailnet name just before installation. Will update later.

**Comment by ajitid** [comment]
Closing this as doctopus could verify that Telltail is able to run both on M series and Intel based Mac. Rushabh, if it doesn't work for you let me know. We can reopen this.

**Comment by doctopus** [comment]
Thank you so much for help.
