### ISSUE TITLE
Telltail is installed but not working? 

### ISSUE THREAD

**Issue by avinashsonee** [ajitid/telltail-center#5]
On Windows 10 x64, I got the telltail center installed via the executable and I'm seeing 'telltail' under the machines list in the admin console. When I try to verify the installation, the site 'https://telltail.tailDDDD.ts.net' is not opening.

I was wondering if this is because under the machines list in the admin console, I see that the tailscale version of telltail is 1.38.1-dev20230316 while my windows machine and other devices are on 1.48.1.

Do let me know the debuggingsteps.

Thank you

**Comment by ajitid** [comment]
Heya! I'll take a look this weekend. Version mismatch should not cause any issue.

**Comment by ajitid** [comment]
Yes you're right, it is not working. Upgrading Tailscale's version to 1.48.1 doesn't resolve the issue either. 

I'm not using this project anymore and I'm also quite occupied with other things so unfortunately I can't help you with this either. PRs are welcome though, if you or anyone could fix this I'd happily accept the changes.

In the meantime, I'll suggest you to subscribe and upvote to https://github.com/tailscale/tailscale/issues/4996 to have this feature implemented natively.

**Comment by ajitid** [comment]
Heya, it is working again. You can uninstall any leftover Telltail program [using this way](https://guide-on.gitbook.io/telltail/installation/uninstall) and setup Telltail again by following [this guide](https://guide-on.gitbook.io/telltail/installation/setup-telltail-center).

**Comment by ajitid** [comment]
Closing the ticket due to staleness.
